import json
import os
from typing import Dict, List, Optional

MOCK_WEBHOOK_URL = os.environ.get(
    "SLACK_WEBHOOK_URL",
    "https://hooks.slack.com/services/T00/B00/MOCK",
)


def _build_blocks(summary: Dict) -> List[Dict]:
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"📋 {summary.get('meeting_title', 'Meeting Summary')}",
            },
        },
        {"type": "divider"},
    ]

    attendees = summary.get("attendees", [])
    if attendees:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Attendees:* {', '.join(attendees)}",
            },
        })

    decisions = summary.get("key_decisions", [])
    if decisions:
        text = "*Key Decisions:*\n" + "\n".join(f"• {d}" for d in decisions)
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": text}})

    actions = summary.get("action_items", [])
    if actions:
        lines = ["*Action Items:*"]
        for a in actions:
            assignee = a.get("assignee", "?")
            deadline = a.get("deadline")
            dl = f"  · *Due:* {deadline}" if deadline else ""
            lines.append(f"• {a['task']}  · *Owner:* {assignee}{dl}")
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "\n".join(lines)},
        })

    risks = summary.get("risks_blockers", [])
    if risks:
        text = "*Risks / Blockers:*\n" + "\n".join(f"⚠ {r}" for r in risks)
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": text}})

    slots = summary.get("suggested_slots", [])
    if slots:
        lines = ["*Suggested Follow-up Slots:*"]
        for s in slots:
            lines.append(f"• {s['date']} at {s['time']} ({s['duration_min']} min)")
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "\n".join(lines)},
        })

    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "🤖 Generated by Meeting Summarizer Agent",
            }
        ],
    })

    return blocks


def post_to_slack(summary: Dict, webhook_url: Optional[str] = None) -> bool:
    """Post a formatted meeting summary to Slack via webhook (mock).

    In production, replace the print() call with:
        import requests
        resp = requests.post(url, json={"blocks": blocks})
        resp.raise_for_status()
    """
    url = webhook_url or MOCK_WEBHOOK_URL
    blocks = _build_blocks(summary)
    payload = {"blocks": blocks}

    print("\n" + "=" * 60)
    print("  SLACK NOTIFICATION (mock)")
    print("=" * 60)
    print(f"  Webhook: {url}")
    print(f"  Payload:\n{json.dumps(payload, indent=2)}")
    print("=" * 60 + "\n")

    return True
